# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap



class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(805, 600)
        self.lblSalidaRespuesta = QtWidgets.QLabel(Widget)
        self.lblSalidaRespuesta.setGeometry(QtCore.QRect(230, 350, 581, 101))
        self.lblSalidaRespuesta.setStyleSheet("color: rgb(0, 0, 255);\n"
                                     "font: 30pt \"Sans serif\";\n"
                                              "font-weight: bold;")
        self.lblSalidaRespuesta.setObjectName("lblSalida")
        self.TXTpWD = QtWidgets.QTextEdit(Widget)
        self.TXTpWD.setGeometry(QtCore.QRect(330, 195, 331, 30))
        self.TXTpWD.setObjectName("TXTpWD")
        self.btnPwd = QtWidgets.QPushButton(Widget)
        self.btnPwd.setGeometry(QtCore.QRect(390, 255, 201, 51))
        self.btnPwd.setObjectName("btnPwd")

        self.lblSalidaTexto = QtWidgets.QLabel(Widget)
        self.lblSalidaTexto.setGeometry(QtCore.QRect(120, 358, 581, 101))
        self.lblSalidaTexto.setStyleSheet("color: rgb(0, 0, 0);\n"
                                     "font: 30pt \"Sans serif\";\n"
                                          "font-weight: bold;")

        self.lblTextoPeticion = QtWidgets.QLabel(Widget)
        self.lblTextoPeticion.setGeometry(QtCore.QRect(120, 170, 331, 71))
        self.lblTextoPeticion.setStyleSheet("color: rgb(0, 0, 0);\n"
                                     "font: 30pt \"Sans serif\";\n"
                                     "font-weight: bold;")
        self.lblTextoPeticion.setObjectName("lblTextoPeticion")

        self.lblTitulo = QtWidgets.QLabel(Widget)
        self.lblTitulo.setGeometry(
            QtCore.QRect(250, 20, 550, 70))  # Ajusta las coordenadas y el tamaño según tus necesidades
        self.lblTitulo.setObjectName("lblTitulo")
        self.lblTitulo.setStyleSheet("color: rgb(0, 0, 0);\n"
                                     "font: 30pt \"Sans serif\";\n"
                                     "font-weight: bold;")

        self.lblImagen = QtWidgets.QLabel(Widget)
        self.lblImagen.setGeometry(
            QtCore.QRect(25, 10, 250, 100))  # Ajusta las coordenadas y el tamaño según tus necesidades
        self.lblImagen.setObjectName("lblImagen")


        # Cargar la imagen desde el archivo y escalarla para ajustarla en el QLabel
        imagen = QPixmap("png/logo_eafit_completo.png")
        imagen = imagen.scaled(200, 200, aspectRatioMode=QtCore.Qt.KeepAspectRatio)
        self.lblImagen.setPixmap(imagen)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "UNIVERSIDAD EAFIT - LENGUAJES DE PROGRAMACIÓN - PROYECTO FINAL"))
        self.lblSalidaRespuesta.setText(_translate("Widget", ""))
        self.btnPwd.setText(_translate("Widget", "Procesar Cadena De Texto"))
        self.lblSalidaTexto.setText(_translate("Widget", "Salida:"))
        self.lblTextoPeticion.setText(_translate("Widget", "Ingrese Texto:"))
        self.lblTitulo.setText("UNIVERSIDAD EAFIT PROYECTO FINAL \n LENGUAJES DE PROGRAMACIÓN")
